#!/usr/bin/env python
"""Run notebook-equivalent Marmousi2 acoustic validation for bv1.2.

The script intentionally mirrors the validation notebooks:

- ``forward`` builds the true Marmousi2 model, source/receiver survey, acoustic
  propagator, and observed data under ``outputs/minimal_notebook``.
- ``inversion10`` and ``inversion100`` build the initial model, read the
  observed data generated by ``forward``, and run AcousticFWI.

It is not a wrapper around ``scripts/examples``. Keep this file close to the
notebook order so script and Jupyter validation stay comparable.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional


REPO_ROOT = Path(__file__).resolve().parents[4]
VALIDATION_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = VALIDATION_ROOT / "outputs" / "minimal_notebook"


@dataclass(frozen=True)
class StagePlan:
    name: str
    description: str
    output_root: Path
    parameters: Dict[str, Any]


def json_default(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    return value


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True, default=json_default) + "\n")


def import_runtime_modules():
    import numpy as np
    import torch
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from scipy import integrate

    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    os.chdir(REPO_ROOT)

    import ADFWI
    from ADFWI.fwi import AcousticFWI
    from ADFWI.fwi.misfit import Misfit_global_correlation, Misfit_waveform_L2
    from ADFWI.model import AcousticModel
    from ADFWI.propagator import AcousticPropagator, GradProcessor
    from ADFWI.survey import Receiver, SeismicData, Source, Survey
    from ADFWI.utils import get_smooth_marmousi_model, load_marmousi_model, resample_marmousi_model, wavelet
    from ADFWI.view import plot_damp

    return {
        "np": np,
        "torch": torch,
        "plt": plt,
        "integrate": integrate,
        "ADFWI": ADFWI,
        "AcousticFWI": AcousticFWI,
        "Misfit_global_correlation": Misfit_global_correlation,
        "Misfit_waveform_L2": Misfit_waveform_L2,
        "AcousticModel": AcousticModel,
        "AcousticPropagator": AcousticPropagator,
        "GradProcessor": GradProcessor,
        "Receiver": Receiver,
        "SeismicData": SeismicData,
        "Source": Source,
        "Survey": Survey,
        "get_smooth_marmousi_model": get_smooth_marmousi_model,
        "load_marmousi_model": load_marmousi_model,
        "resample_marmousi_model": resample_marmousi_model,
        "wavelet": wavelet,
        "plot_damp": plot_damp,
    }


def ensure_output_dirs(output_root: Path, *, inversion: bool = False) -> None:
    subdirs = ["model", "waveform", "survey"]
    if inversion:
        subdirs.append("inversion")
    for subdir in subdirs:
        (output_root / subdir).mkdir(parents=True, exist_ok=True)


def cumulative_source_wavelet(rt: Dict[str, Any], nt: int, dt: float, f0: float):
    np = rt["np"]
    integrate = rt["integrate"]
    _, src_v = rt["wavelet"](nt, dt, f0, amp0=1)
    try:
        return integrate.cumtrapz(src_v, axis=-1, initial=0)
    except AttributeError:
        return integrate.cumulative_trapezoid(src_v, axis=-1, initial=0)


def build_survey(rt: Dict[str, Any], args: argparse.Namespace):
    np = rt["np"]
    Source = rt["Source"]
    Receiver = rt["Receiver"]
    Survey = rt["Survey"]

    src_z = np.array([1 for _ in range(2, args.nx - 1, 5)])[: args.shots]
    src_x = np.array([i for i in range(2, args.nx - 1, 5)])[: args.shots]
    src_v = cumulative_source_wavelet(rt, args.nt, args.dt, args.f0)

    source = Source(nt=args.nt, dt=args.dt, f0=args.f0)
    for i in range(len(src_x)):
        source.add_source(
            src_x=src_x[i],
            src_z=src_z[i],
            src_wavelet=src_v,
            src_type="mt",
            src_mt=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]),
        )

    rcv_z = np.array([1 for _ in range(0, args.nx, 1)])
    rcv_x = np.array([j for j in range(0, args.nx, 1)])
    receiver = Receiver(nt=args.nt, dt=args.dt)
    for i in range(len(rcv_x)):
        receiver.add_receiver(rcv_x=rcv_x[i], rcv_z=rcv_z[i], rcv_type="pr")

    return Survey(source=source, receiver=receiver)


def build_true_arrays(rt: Dict[str, Any], args: argparse.Namespace):
    np = rt["np"]
    marmousi_model = rt["load_marmousi_model"](in_dir=str(args.dataset_dir))
    x = np.linspace(5000, 5000 + args.dx * args.nx, args.nx)
    z = np.linspace(0, args.dz * args.nz, args.nz)
    true_model = rt["resample_marmousi_model"](x, z, marmousi_model)
    vp_true = true_model["vp"].T
    rho_true = np.power(vp_true, 0.25) * 310
    return true_model, vp_true, rho_true


def build_true_model(rt: Dict[str, Any], args: argparse.Namespace):
    AcousticModel = rt["AcousticModel"]
    _, vp_true, rho_true = build_true_arrays(rt, args)
    return AcousticModel(
        args.ox,
        args.oz,
        args.nx,
        args.nz,
        args.dx,
        args.dz,
        vp_true,
        rho_true,
        vp_grad=False,
        free_surface=args.free_surface,
        abc_type=args.abc_type,
        abc_jerjan_alpha=args.abc_jerjan_alpha,
        nabc=args.nabc,
        device=args.device,
        dtype=rt["torch"].float32 if args.dtype == "float32" else rt["torch"].float64,
    )


def build_initial_model(rt: Dict[str, Any], args: argparse.Namespace):
    np = rt["np"]
    AcousticModel = rt["AcousticModel"]
    true_model, vp_true, _ = build_true_arrays(rt, args)
    smooth_model = rt["get_smooth_marmousi_model"](
        true_model,
        gaussian_kernel=args.gaussian_kernel,
        rcv_depth=args.rcv_depth,
        mask_extra_detph=args.mask_extra_depth,
    )
    vp_init = smooth_model["vp"].T
    rho_init = np.power(vp_init, 0.25) * 310
    model = AcousticModel(
        args.ox,
        args.oz,
        args.nx,
        args.nz,
        args.dx,
        args.dz,
        vp_init,
        rho_init,
        vp_bound=[vp_true.min(), vp_true.max()],
        vp_grad=True,
        free_surface=args.free_surface,
        abc_type=args.abc_type,
        abc_jerjan_alpha=args.abc_jerjan_alpha,
        nabc=args.nabc,
        auto_update_rho=True,
        device=args.device,
        dtype=rt["torch"].float32 if args.dtype == "float32" else rt["torch"].float64,
    )
    return model, vp_init, vp_true


def tensor_summary(rt: Dict[str, Any], value) -> Dict[str, Any]:
    torch = rt["torch"]
    detached = value.detach()
    return {
        "shape": list(detached.shape),
        "device": str(detached.device),
        "dtype": str(detached.dtype).replace("torch.", ""),
        "finite": bool(torch.isfinite(detached).all().item()),
        "min": float(detached.min().cpu().item()),
        "max": float(detached.max().cpu().item()),
        "norm": float(torch.linalg.norm(detached.reshape(-1)).cpu().item()),
    }


def save_forward_figures(rt: Dict[str, Any], output_root: Path, model, survey, source, propagator, d_obs) -> None:
    source.plot_wavelet(save_path=str(output_root / "survey" / "wavelets.png"))
    survey.plot(model.vp, cmap="coolwarm", save_path=str(output_root / "survey" / "observed_system.png"))
    rt["plot_damp"](propagator.damp, save_path=str(output_root / "model" / "boundary_condition.png"))
    d_obs.plot_waveform2D(
        i_shot=0,
        rcv_type="pressure",
        acoustic_or_elastic="acoustic",
        normalize=False,
        figsize=(6, 6),
        cmap="coolwarm",
        save_path=str(output_root / "waveform" / "obs_2D_shot_0.png"),
        show=False,
    )
    d_obs.plot_waveform_wiggle(
        i_shot=0,
        rcv_type="pressure",
        acoustic_or_elastic="acoustic",
        normalize=False,
        save_path=str(output_root / "waveform" / "obs_wiggle_shot_0.png"),
        show=False,
    )
    d_obs.plot_waveform_trace(
        i_shot=0,
        i_trace=min(100, survey.receiver.num - 1),
        rcv_type="pressure",
        acoustic_or_elastic="acoustic",
        normalize=False,
        save_path=str(output_root / "waveform" / "obs_trace_shot_0_trace_100.png"),
        show=False,
    )


def run_check(args: argparse.Namespace) -> Dict[str, Any]:
    rt = import_runtime_modules()
    rt["ADFWI"].set_backend(args.device, dtype=args.dtype, fallback=args.fallback_cpu)
    ensure_output_dirs(args.output_root)
    model = build_true_model(rt, args)
    survey = build_survey(rt, args)
    propagator = rt["AcousticPropagator"](model, survey, device=args.device)
    return {
        "status": "ok",
        "stage": "check",
        "output_root": str(args.output_root),
        "backend": rt["ADFWI"].backend_diagnostics(),
        "model": {"vp": tensor_summary(rt, model.vp), "rho": tensor_summary(rt, model.rho)},
        "survey": {"shots": survey.source.num, "receivers": survey.receiver.num, "nt": survey.source.nt, "dt": survey.source.dt},
        "propagator": {"device": str(propagator.device), "dtype": str(propagator.dtype).replace("torch.", "")},
    }


def run_forward(args: argparse.Namespace) -> Dict[str, Any]:
    rt = import_runtime_modules()
    backend = rt["ADFWI"].set_backend(args.device, dtype=args.dtype, fallback=args.fallback_cpu)
    torch = rt["torch"]
    ensure_output_dirs(args.output_root)

    model = build_true_model(rt, args)
    model.save(str(args.output_root / "model" / "true_model.npz"))
    model._plot_vp_rho(
        figsize=(12, 5),
        wspace=0.15,
        cbar_pad_fraction=0.02,
        cmap="coolwarm",
        save_path=str(args.output_root / "model" / "true_vp_rho.png"),
    )

    survey = build_survey(rt, args)
    propagator = rt["AcousticPropagator"](model, survey, device=args.device)
    if backend.name in {"cuda", "npu"}:
        backend.synchronize()
    start = time.perf_counter()
    with torch.no_grad():
        record_waveform = propagator.forward(checkpoint_segments=args.checkpoint_segments)
    if backend.name in {"cuda", "npu"}:
        backend.synchronize()
    seconds = time.perf_counter() - start

    d_obs = rt["SeismicData"](survey)
    d_obs.record_data(record_waveform)
    obs_path = args.output_root / "waveform" / "obs_data.npz"
    d_obs.save(str(obs_path))
    save_forward_figures(rt, args.output_root, model, survey, survey.source, propagator, d_obs)

    report = {
        "status": "ok",
        "stage": "forward",
        "output_root": str(args.output_root),
        "obs_data": str(obs_path),
        "backend": rt["ADFWI"].backend_diagnostics(),
        "seconds": seconds,
        "checkpoint_segments": args.checkpoint_segments,
        "survey": {"shots": survey.source.num, "receivers": survey.receiver.num, "nt": survey.source.nt, "dt": survey.source.dt},
        "record": {"p": tensor_summary(rt, record_waveform["p"])},
    }
    write_json(args.output_root / "forward_summary.json", report)
    return report


def run_inversion(args: argparse.Namespace, *, iterations: int) -> Dict[str, Any]:
    rt = import_runtime_modules()
    backend = rt["ADFWI"].set_backend(args.device, dtype=args.dtype, fallback=args.fallback_cpu)
    np = rt["np"]
    torch = rt["torch"]
    plt = rt["plt"]
    ensure_output_dirs(args.output_root, inversion=True)

    obs_path = args.output_root / "waveform" / "obs_data.npz"
    if not obs_path.exists():
        raise FileNotFoundError(f"missing observed data: {obs_path}; run the forward stage first")

    model, vp_init, vp_true = build_initial_model(rt, args)
    model.save(str(args.output_root / "model" / "init_model.npz"))
    model._plot_vp_rho(
        figsize=(12, 5),
        wspace=0.15,
        cbar_pad_fraction=0.01,
        cmap="coolwarm",
        save_path=str(args.output_root / "model" / "init_vp_rho.png"),
    )

    survey = build_survey(rt, args)
    survey.plot(model.vp, cmap="coolwarm", save_path=str(args.output_root / "survey" / "observed_system_init.png"))
    propagator = rt["AcousticPropagator"](model, survey, device=args.device)
    rt["plot_damp"](propagator.damp, save_path=str(args.output_root / "model" / "boundary_condition.png"))

    d_obs = rt["SeismicData"](survey)
    d_obs.load(str(obs_path))

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=args.scheduler_step_size, gamma=args.scheduler_gamma, last_epoch=-1)
    loss_fn = rt["Misfit_waveform_L2"](dt=1)
    grad_mask = np.ones_like(vp_init)
    grad_mask[: args.grad_mute_top, :] = 0
    gradient_processor = rt["GradProcessor"](grad_mask=grad_mask)

    fwi = rt["AcousticFWI"](
        propagator=propagator,
        model=model,
        optimizer=optimizer,
        scheduler=scheduler,
        loss_fn=loss_fn,
        obs_data=d_obs,
        gradient_processor=gradient_processor,
        waveform_normalize=True,
        cache_result=True,
        save_fig_epoch=50,
        save_fig_path=str(args.output_root / "inversion"),
    )

    if backend.name in {"cuda", "npu"}:
        backend.synchronize()
    start = time.perf_counter()
    fwi.forward(iteration=iterations, batch_size=args.shots, checkpoint_segments=args.checkpoint_segments)
    if backend.name in {"cuda", "npu"}:
        backend.synchronize()
    seconds = time.perf_counter() - start

    iter_vp = fwi.iter_vp
    iter_loss = [float(value) for value in fwi.iter_loss]
    np.savez(args.output_root / "inversion" / "iter_vp.npz", data=np.array(iter_vp))
    np.savez(args.output_root / "inversion" / "iter_loss.npz", data=np.array(iter_loss))

    plt.figure(figsize=(8, 6))
    plt.plot(iter_loss, c="k")
    plt.xlabel("Iteration")
    plt.ylabel("Misfit")
    plt.grid(True, alpha=0.3)
    plt.savefig(args.output_root / "inversion" / "loss.png", bbox_inches="tight")
    plt.close()

    final_vp = iter_vp[-1]
    plt.figure(figsize=(12, 8))
    plt.subplot(121)
    plt.imshow(vp_init, cmap="coolwarm")
    plt.title("Initial vp")
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.subplot(122)
    plt.imshow(final_vp, cmap="coolwarm")
    plt.title("Inverted vp")
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.savefig(args.output_root / "inversion" / "init_vs_inverted_vp.png", bbox_inches="tight")
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.subplot(121)
    plt.imshow(vp_true, cmap="coolwarm")
    plt.title("True vp")
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.subplot(122)
    plt.imshow(final_vp, cmap="coolwarm")
    plt.title("Inverted vp")
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.savefig(args.output_root / "inversion" / "true_vs_inverted_vp.png", bbox_inches="tight")
    plt.close()

    report = {
        "status": "ok",
        "stage": "inversion",
        "output_root": str(args.output_root),
        "obs_data": str(obs_path),
        "backend": rt["ADFWI"].backend_diagnostics(),
        "iterations": iterations,
        "shots": args.shots,
        "checkpoint_segments": args.checkpoint_segments,
        "seconds": seconds,
        "initial_loss": iter_loss[0],
        "final_loss": iter_loss[-1],
        "loss_history": iter_loss,
        "vp_update_norm": float(torch.linalg.norm((model.vp.detach() - torch.as_tensor(vp_init, device=model.vp.device, dtype=model.vp.dtype)).reshape(-1)).cpu().item()),
    }
    write_json(args.output_root / "inversion" / f"inversion{iterations}_summary.json", report)
    return report


def stage_iterations(args: argparse.Namespace, stage: str) -> int:
    if args.iterations is not None:
        return args.iterations
    if stage == "inversion100":
        return 100
    return 10


def build_stage_plans(args: argparse.Namespace) -> List[StagePlan]:
    stages = ["check", "forward", "inversion10"] if args.stage == "all" else [args.stage]
    plans = []
    for stage in stages:
        parameters = {
            "device": args.device,
            "dtype": args.dtype,
            "shots": args.shots,
            "nt": args.nt,
            "dt": args.dt,
            "f0": args.f0,
            "checkpoint_segments": args.checkpoint_segments,
            "output_root": args.output_root,
        }
        if stage in {"inversion10", "inversion100"}:
            parameters.update({"iterations": stage_iterations(args, stage), "lr": args.lr})
        plans.append(
            StagePlan(
                name=stage,
                description={
                    "check": "build true model, survey, backend, and propagator without propagation",
                    "forward": "notebook-equivalent true-model forward that writes obs_data.npz",
                    "inversion10": "notebook-equivalent inversion using forward-generated obs_data.npz",
                    "inversion100": "longer notebook-equivalent inversion using forward-generated obs_data.npz",
                }[stage],
                output_root=args.output_root,
                parameters=parameters,
            )
        )
    return plans


def dry_run_payload(plans: Iterable[StagePlan]) -> Dict[str, object]:
    return {
        "status": "ok",
        "stages": [
            {
                "stage": plan.name,
                "description": plan.description,
                "output_root": plan.output_root,
                "parameters": plan.parameters,
            }
            for plan in plans
        ],
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stage", choices=("check", "forward", "inversion10", "inversion100", "all"))
    parser.add_argument("--device", default="npu:0", help="cpu, npu:0, cuda:0, or auto")
    parser.add_argument("--dtype", default="float32", choices=("float32", "float64"))
    parser.add_argument("--fallback-cpu", action="store_true")
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--dataset-dir", type=Path, default=REPO_ROOT / "examples" / "datasets" / "marmousi2_source")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--shots", type=int, default=3)
    parser.add_argument("--iterations", type=int, help="override inversion iterations")
    parser.add_argument("--checkpoint-segments", type=int, default=1)
    parser.add_argument("--lr", type=float, default=10.0)
    parser.add_argument("--scheduler-step-size", type=int, default=200)
    parser.add_argument("--scheduler-gamma", type=float, default=0.75)
    parser.add_argument("--grad-mute-top", type=int, default=12)
    parser.add_argument("--ox", type=float, default=0.0)
    parser.add_argument("--oz", type=float, default=0.0)
    parser.add_argument("--nx", type=int, default=200)
    parser.add_argument("--nz", type=int, default=88)
    parser.add_argument("--dx", type=float, default=40.0)
    parser.add_argument("--dz", type=float, default=40.0)
    parser.add_argument("--nt", type=int, default=3000)
    parser.add_argument("--dt", type=float, default=0.003)
    parser.add_argument("--nabc", type=int, default=30)
    parser.add_argument("--f0", type=float, default=5.0)
    parser.add_argument("--free-surface", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--abc-type", default="PML")
    parser.add_argument("--abc-jerjan-alpha", type=float, default=0.007)
    parser.add_argument("--gaussian-kernel", type=int, default=6)
    parser.add_argument("--rcv-depth", type=int, default=10)
    parser.add_argument("--mask-extra-depth", type=int, default=2)
    return parser


def run_stage(args: argparse.Namespace, stage: str) -> Dict[str, Any]:
    if stage == "check":
        return run_check(args)
    if stage == "forward":
        return run_forward(args)
    if stage in {"inversion10", "inversion100"}:
        return run_inversion(args, iterations=stage_iterations(args, stage))
    raise ValueError(f"unsupported stage: {stage}")


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.shots <= 0:
        parser.error("--shots must be positive")
    if args.iterations is not None and args.iterations <= 0:
        parser.error("--iterations must be positive")

    plans = build_stage_plans(args)
    if args.dry_run:
        print(json.dumps(dry_run_payload(plans), indent=2, sort_keys=True, default=json_default))
        return 0

    reports = []
    stages = [plan.name for plan in plans]
    try:
        for stage in stages:
            reports.append(run_stage(args, stage))
    except Exception as exc:
        print(json.dumps({"status": "failed", "stage": stage, "error": repr(exc)}, indent=2), file=sys.stderr)
        return 1

    print(json.dumps({"status": "ok", "stages": reports}, indent=2, sort_keys=True, default=json_default))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
